Instance launch on second compute node is failing
Instance launch on first compute node is successful
but on second compute node it is failing with error

HTTPError: 400,8: The value of name does not provide
a unique value for the corresponding data model property as required

Closes-Bug: #1703768

Change-Id: I67923dd4d62d690a7dabc38c0cdb47d593b8e11a
Signed-off-by: Prabhat Ranjan <pranjank@in.ibm.com>