Docs: Fix RTD docs build process
Since commit 8f82f0a4 ReadTheDocs (RTD) wasn't able to build the docs.
The stacktrace from the RTD build show this error:

  ExtensionError: Could not import extension oslo_config.sphinxconfiggen
  (exception: No module named oslo_config.sphinxconfiggen)

The reason is, that RTD *doesn't* use tox targets to create the docs.
It also cannot be configured to use tox. It uses it's own chain of
commands to build, like these (simplified) commands:

  $ python -mvirtualenv  nova-dpm/envs/latest
  $ python nova-dpm/envs/latest/bin/pip install -r test-requirements.txt
  $ python nova-dpm/envs/latest/bin/sphinx-build -T -E \
  -b readthedocs . _build/html

This means RTD is not able to pull in the dependencies we specified in
the "tox.ini" base target:

    [testenv]
    deps = -r{toxinidir}/test-requirements.txt
           -r{toxinidir}/requirements.txt
           -egit+https://github.com/openstack/nova#egg=nova

The needed python package is "oslo.config", which gets pulled into our
tox targets via the specified dependency to nova, that's why the initial
commit didn't fail the docs testing job.

This change introduces a dedicated "docs-requirements.txt" file, which
will only be used by building docs. All existing docs dependencies got
moved into that requirements file. This file will then be used by the
RTD project and the upstream docs test job.

An alternative approach would have been to simply add "oslo.config" to
"test-requirements.txt", but that wouldn't stop similar issues in the
future, that's why I've chosen the approach mentioned above.

Closes bug: 1660572

Change-Id: I0ee08daacb21a4b1e82c035be49b3a84b4f3c7fb